name = "pendlings-app1"
compatibility_date = "2026-05-14"

[assets]
directory = "."

[[assets.headers]]
styles = ["/sitemap.xml"]
[assets.headers.values]
Content-Type = "application/xml; charset=utf-8"
Cache-Control = "public, max-age=86400"
